//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "pit_responses_2022")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub author: i32,
    pub timestamp: i32,
    pub team: i32,
    pub name: Option<String>,
    pub drivetrain: i32,
    pub size_x: i32,
    pub size_y: i32,
    pub size_z: i32,
    pub climb: i32,
    pub auto_where_shoot: i32,
    pub auto_shots: i32,
    pub auto_taxi: i32,
    pub teleop_where_shoot: i32,
    pub teleop_shots: i32,
    pub image: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
