//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

pub use super::images::Entity as Images;
pub use super::match_responses_2022::Entity as MatchResponses2022;
pub use super::pit_responses_2022::Entity as PitResponses2022;
pub use super::users::Entity as Users;
